---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- flux-image-repository.yaml

patchesStrategicMerge:
- aws-load-balancer-controller-patch.yaml
- backend-patch.yaml