name: Backend Security Audit
# on:
#   push:
#     paths:
#       - '**/Cargo.toml'
#       - '**/Cargo.lock'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  security_audit:
    defaults:
      run:
        working-directory: ./application/backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}